[package]
name = "trusted_applet"
version = "0.1.0"
edition = "2021"
description = "Rust Trusted Applet for USB Armory MK II (GoTEE)"

[[bin]]
name = "trusted_applet"
path = "../src/main.rs"

[dependencies]
gotee_syscall = { path = "gotee_syscall" }

sha2 = { version = "0.10", default-features = false }

hmac = { version = "0.12", default-features = false }

[profile.release]
panic = "abort"
opt-level = "s"
lto = true
codegen-units = 1